<a href="https://colab.research.google.com/github/CreatorDave/201lab05a/blob/main/Pandas_Data_Manipulation_Tasks_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

# Sample sales data
df_sales = pd.DataFrame({
    'Store': ['A', 'B', 'A', 'C', 'B', 'C', 'A'],
    'Product': ['Apples', 'Oranges', 'Bananas', 'Apples', 'Bananas', 'Oranges', 'Bananas'],
    'Units_Sold': [30, 45, 20, 25, 30, 40, 50],
    'Price': [1.0, 0.8, 0.5, 1.2, 0.55, 0.75, 0.6],
    'Date': pd.to_datetime([
        '2024-01-01', '2024-01-02', '2024-01-03', '2024-01-01',
        '2024-01-02', '2024-01-03', '2024-01-04'
    ])
})

df_stores = pd.DataFrame({
    'Store': ['A', 'B', 'C'],
    'City': ['Prague', 'Brno', 'Ostrava'],
    'Manager': ['Alice', 'Bob', 'Charlie']
})

### Task 1: Preview the first 2 few rows of both DataFrames

In [4]:
# Your code here
df_sales.head(2)
df_stores.head(2)
print(df_sales)
print(df_stores)

  Store  Product  Units_Sold  Price       Date
0     A   Apples          30   1.00 2024-01-01
1     B  Oranges          45   0.80 2024-01-02
2     A  Bananas          20   0.50 2024-01-03
3     C   Apples          25   1.20 2024-01-01
4     B  Bananas          30   0.55 2024-01-02
5     C  Oranges          40   0.75 2024-01-03
6     A  Bananas          50   0.60 2024-01-04
  Store     City  Manager
0     A   Prague    Alice
1     B     Brno      Bob
2     C  Ostrava  Charlie

### Task 2: Create a new column `Revenue` as Units_Sold * Price

In [5]:
# Your code here
df_sales['Revenue'] = df_sales['Units_Sold'] * df_sales['Price']
print(df_sales)

  Store  Product  Units_Sold  Price       Date  Revenue
0     A   Apples          30   1.00 2024-01-01     30.0
1     B  Oranges          45   0.80 2024-01-02     36.0
2     A  Bananas          20   0.50 2024-01-03     10.0
3     C   Apples          25   1.20 2024-01-01     30.0
4     B  Bananas          30   0.55 2024-01-02     16.5
5     C  Oranges          40   0.75 2024-01-03     30.0
6     A  Bananas          50   0.60 2024-01-04     30.0

### Task 3: Filter the rows to include only sales of Bananas

In [6]:
# Your code here
df_sales[df_sales['Product'] == 'Bananas']

  Store  Product  Units_Sold  Price       Date  Revenue
2     A  Bananas          20   0.50 2024-01-03     10.0
4     B  Bananas          30   0.55 2024-01-02     16.5
6     A  Bananas          50   0.60 2024-01-04     30.0

### Task 4: Filter the rows for sales after January 2, 2024

In [7]:
# Your code here
df_sales[df_sales['Date'] > '2024-01-02']

  Store  Product  Units_Sold  Price       Date  Revenue
2     A  Bananas          20   0.50 2024-01-03     10.0
5     C  Oranges          40   0.75 2024-01-03     30.0
6     A  Bananas          50   0.60 2024-01-04     30.0

### Task 5: Group by `Product` and calculate total units sold

In [8]:
# Your code here
df_sales.groupby('Product')['Units_Sold'].sum()

Product
Apples      55
Bananas    100
Oranges     85
Name: Units_Sold, dtype: int64

### Task 6: Group by `Store` and `Product`, and show total revenue

In [9]:
# Your code here
df_sales.groupby(['Store', 'Product'])['Revenue'].sum()

Store  Product
A      Apples     30.0
       Bananas    40.0
B      Bananas    16.5
       Oranges    36.0
C      Apples     30.0
       Oranges    30.0
Name: Revenue, dtype: float64

### Task 7: Merge `df_sales` with `df_stores` on the `Store` column

In [10]:
# Your code here
df_sales.merge(df_stores, on='Store')

  Store  Product  Units_Sold  Price       Date  Revenue     City  Manager
0     A   Apples          30   1.00 2024-01-01     30.0   Prague    Alice
1     B  Oranges          45   0.80 2024-01-02     36.0     Brno      Bob
2     A  Bananas          20   0.50 2024-01-03     10.0   Prague    Alice
3     C   Apples          25   1.20 2024-01-01     30.0  Ostrava  Charlie
4     B  Bananas          30   0.55 2024-01-02     16.5     Brno      Bob
5     C  Oranges          40   0.75 2024-01-03     30.0  Ostrava  Charlie
6     A  Bananas          50   0.60 2024-01-04     30.0   Prague    Alice

### Task 8: Sort the sales by `Revenue` in descending order

In [11]:
# Your code here
df_sales.sort_values(by='Revenue', ascending=False)

  Store  Product  Units_Sold  Price       Date  Revenue
1     B  Oranges          45   0.80 2024-01-02     36.0
0     A   Apples          30   1.00 2024-01-01     30.0
3     C   Apples          25   1.20 2024-01-01     30.0
6     A  Bananas          50   0.60 2024-01-04     30.0
5     C  Oranges          40   0.75 2024-01-03     30.0
4     B  Bananas          30   0.55 2024-01-02     16.5
2     A  Bananas          20   0.50 2024-01-03     10.0

### Task 9: Introduce a missing value and fill it with the mean

In [12]:
# Your code here
df_sales.loc[0, 'Units_Sold'] = np.nan
df_sales.fillna(df_sales['Units_Sold'].mean())

  Store  Product  Units_Sold  Price       Date  Revenue
0     A   Apples        35.0   1.00 2024-01-01     30.0
1     B  Oranges        45.0   0.80 2024-01-02     36.0
2     A  Bananas        20.0   0.50 2024-01-03     10.0
3     C   Apples        25.0   1.20 2024-01-01     30.0
4     B  Bananas        30.0   0.55 2024-01-02     16.5
5     C  Oranges        40.0   0.75 2024-01-03     30.0
6     A  Bananas        50.0   0.60 2024-01-04     30.0

### Task 10: Create a new boolean column `High_Seller` for Units_Sold > 30

In [13]:
# Your code here
df_sales['High_Seller'] = df_sales['Units_Sold'] > 30
print(df_sales)

  Store  Product  Units_Sold  Price       Date  Revenue  High_Seller
0     A   Apples         NaN   1.00 2024-01-01     30.0        False
1     B  Oranges        45.0   0.80 2024-01-02     36.0         True
2     A  Bananas        20.0   0.50 2024-01-03     10.0        False
3     C   Apples        25.0   1.20 2024-01-01     30.0        False
4     B  Bananas        30.0   0.55 2024-01-02     16.5        False
5     C  Oranges        40.0   0.75 2024-01-03     30.0         True
6     A  Bananas        50.0   0.60 2024-01-04     30.0         True