<a href="https://colab.research.google.com/github/CreatorDave/201lab05a/blob/main/Sample_Orders_Coding_Exercise_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practice Exercise: Analyze Sample Orders Data Using Pandas

**Objective**: Use your knowledge of Python and Pandas to explore and analyze a dataset.

**Instructions**: Complete the tasks below by writing code in the provided code cells. Make sure to run your code to check your results.

## Section 1: Data Loading and Initial Exploration

**Task 1.1:** Import the pandas library.

In [2]:
# Your code here
import pandas as pd

**Task 1.2:** Load the dataset `sample_orders.csv` and display the first 5 rows.

In [4]:
# Your code here
from google.colab import files
uploaded = files.upload()
df = pd.read_csv('sample_orders.csv')
df.head()

Saving sample_orders.csv to sample_orders.csv

,Order ID,Order Date,Ship Date,Region,Category,Sub-Category,Sales,Profit,Segment
0,CA-2017-152156,2017-11-08,2017-11-11,West,Furniture,Bookcases,261.96,41.91,Consumer
1,CA-2017-152157,2017-11-08,2017-11-11,West,Furniture,Chairs,731.94,219.58,Corporate
2,US-2016-108966,2016-10-11,2016-10-18,Central,Technology,Phones,957.58,191.58,Consumer
3,CA-2015-115812,2015-06-09,2015-06-14,West,Office Supplies,Labels,14.62,6.87,Home Office
4,CA-2015-115813,2015-06-09,2015-06-14,West,Office Supplies,Paper,15.60,5.12,Corporate

**Task 1.3:** Print the shape of the dataset, list the column names, and display the data types.

In [5]:
# Your code here
print(df.shape)
print(df.columns)
print(df.dtypes)

(5, 9)
Index(['Order ID', 'Order Date', 'Ship Date', 'Region', 'Category',
       'Sub-Category', 'Sales', 'Profit', 'Segment'],
      dtype='object')
Order ID         object
Order Date       object
Ship Date        object
Region           object
Category         object
Sub-Category     object
Sales           float64
Profit          float64
Segment          object
dtype: object

**Task 1.4:** Check for missing values in the dataset.

In [6]:
# Your code here
print(df.isnull().sum())

Order ID        0
Order Date      0
Ship Date       0
Region          0
Category        0
Sub-Category    0
Sales           0
Profit          0
Segment         0
dtype: int64

## Section 2: Data Preparation

**Task 2.1:** Convert `Order Date` and `Ship Date` columns to datetime format.

In [7]:
# Your code here
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])
print(df.dtypes)

Order ID                object
Order Date      datetime64[ns]
Ship Date       datetime64[ns]
Region                  object
Category                object
Sub-Category            object
Sales                  float64
Profit                 float64
Segment                 object
dtype: object

**Task 2.2:** Create a new column called `Delivery Time (Days)` that calculates the number of days between the order date and ship date.

In [8]:
# Your code here
df['Delivery Time (Days)'] = (df['Ship Date'] - df['Order Date']).dt.days
df.head()

,Order ID,Order Date,Ship Date,Region,Category,Sub-Category,Sales,Profit,Segment,Delivery Time (Days)
0,CA-2017-152156,2017-11-08,2017-11-11,West,Furniture,Bookcases,261.96,41.91,Consumer,3
1,CA-2017-152157,2017-11-08,2017-11-11,West,Furniture,Chairs,731.94,219.58,Corporate,3
2,US-2016-108966,2016-10-11,2016-10-18,Central,Technology,Phones,957.58,191.58,Consumer,7
3,CA-2015-115812,2015-06-09,2015-06-14,West,Office Supplies,Labels,14.62,6.87,Home Office,5
4,CA-2015-115813,2015-06-09,2015-06-14,West,Office Supplies,Paper,15.60,5.12,Corporate,5

## Section 3: Exploratory Data Analysis

**Task 3.1:** Calculate the total sales for each product category. Sort the results from highest to lowest.

In [9]:
# Your code here
df.groupby('Category')['Sales'].sum().sort_values(ascending=False)

Category
Furniture          993.90
Technology         957.58
Office Supplies     30.22
Name: Sales, dtype: float64

**Task 3.2:** Calculate the total profit by region. Sort the results from highest to lowest.

In [10]:
# Your code here
df.groupby('Region')['Profit'].sum().sort_values(ascending=False)

Region
West       273.48
Central    191.58
Name: Profit, dtype: float64

**Task 3.3:** Create a pivot table showing total sales and profit by Category and Sub-Category.

In [11]:
# Your code here
df.pivot_table(index='Category', columns='Sub-Category', values=['Sales', 'Profit'], aggfunc='sum')

                   Profit                                  Sales          \
Sub-Category    Bookcases  Chairs Labels Paper  Phones Bookcases  Chairs
Category
Furniture           41.91  219.58    NaN   NaN     NaN    261.96  731.94
Office Supplies       NaN     NaN   6.87  5.12     NaN       NaN     NaN
Technology            NaN     NaN    NaN   NaN  191.58       NaN     NaN


Sub-Category    Labels Paper  Phones
Category
Furniture          NaN   NaN     NaN
Office Supplies  14.62  15.6     NaN
Technology         NaN   NaN  957.58

## Section 4: Reflection

Answer the following questions in your own words:

- What trends did you observe in the dataset?
- Which categories or regions performed best or worst in terms of sales and profit?
- What other questions could you explore with this data?